AWSTemplateFormatVersion: 2010-09-09
Description: Coudformation template for an S3Bucket with CLoudfront distribution
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: adrians-helloweb-project
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: http://adrians-helloweb-project.s3-website.eu-west-2.amazonaws.com/
          Id: helloweb-s3-website
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
        Enabled: 'true'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: helloweb-s3-website
          SmoothStreaming: 'false'
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: all
          ViewerProtocolPolicy: allow-all
        CustomErrorResponses:
        - ErrorCode: '404'
          ResponsePagePath: "error.html"
          ResponseCode: '200'
          ErrorCachingMinTTL: '30'
        PriceClass: PriceClass_200
        Restrictions:
          GeoRestriction:
            RestrictionType: whitelist
            Locations:
            - GB
            - FR
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
Outputs:
  S3Bucket:
    Description: Bucket details
    Value: !Ref S3Bucket
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL