AWSTemplateFormatVersion: 2010-09-09
Description: Coudformation template for an S3Bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: adrians-helloweb-project
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain


  TestDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: http://adrians-helloweb-project.s3-website.eu-west-2.amazonaws.com/
          Id: helloweb-project
        Enabled: 'true'
        Comment: TestDistribution
        DefaultRootObject: index.html
        CustomErrorResponses:
        - ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
         DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: helloweb-project
          PriceClass: PriceClass_100
Outputs:
  S3Bucket:
    Description: Bucket details
    Value: !Ref S3Bucket
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL