AWSTemplateFormatVersion: 2010-09-09
Description: Coudformation template for an S3Bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: adrians-helloweb-project
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

Outputs:
  S3Bucket:
    Description: Bucket details
    Value: !Ref S3Bucket
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL