name: cf-push

on:
  workflow_dispatch:

jobs:
  auth-and-deploy:
    name: deploy to cfn
    runs-on: ubuntu-latest  
    steps:
  
      uses: actions/checkout@v2
      with:
        ref: main
    
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION}}
    
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: Helloweb-project-deploy
        template: stack.yaml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          Name=${{ steps.env-name.outputs.environment }},
          Repository=https://github.com/${{ github.repository }},
          OauthToken=${{ secrets.PAT_GITHUB }},